swagger: '2.0'
info:
  version: 1.0.0
  title: Yet Another Node.js Blogg Application API
  description: Yet Another Node.js Blogg Application API
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
host: localhost:3000
basePath: /api/v1
tags:
  - name: Users
    description: API for users in the system
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /users:
    post:
      tags:
        - Users
      description: Create new user in system
      parameters:
        - name: user
          in: body
          description: User that we want to create
          schema:
            $ref: '#/definitions/createPassword'
      produces:
        - application/json
      responses:
        '200':
          description: New user is created
          schema:
            $ref: '#/definitions/userCreated'
  
definitions:
  createPassword:
    required:
        - userName
        - passWord
        - confirmPassWord
    properties:
      userName:
        type: string
        uniqueItems: true
      passWord:
        type: string
      confirmPassWord:
        type: string
  userCreated:
    required:
        - userName
        - passWord
        - confirmPassWord
    properties:
      userName:
        type: string
        uniqueItems: true
      passWord:
        type: string
      _id:
        type: string
      __v:
        type: string
      
  
